name: Generate Docs

on:
  workflow_dispatch:


jobs:
  generate-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest  # Use a specific version if needed

      - name: Install jsdoc-to-markdown globally
        run: bun add -g jsdoc-to-markdown markdown-it markdown-it-anchor markdown-it-header-sections markdown-it-highlightjs markdown-it-table-of-contents

      - name: change Directory
        run: cd genDoc

      - name: Install jsdoc-to-markdown locally
        run: bun add jsdoc-to-markdown markdown-it markdown-it-anchor markdown-it-header-sections markdown-it-highlightjs markdown-it-table-of-contents

      - name: Run documentation generation script
        run: bun run index.ts
      
      - name: Configure Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'

      - name: Commit and push changes
        run: |
          git add documentation
          git add lib
          git commit -m "Update generated documentation"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
